config/routes.rb
Spree::Core::Engine.add_routes do
  resources :wishlists
  resources :wished_products, only: [:create, :update, :destroy]
  get '/wishlist' => 'wishlists#default', as: 'default_wishlist'
end

app/models/spree/user_decorator.rb
Spree.user_class.class_eval do
  has_many :wishlists, class_name: Spree::Wishlist.to_s

  def wishlist
    default_wishlist = wishlists.where(is_default: true).first
    default_wishlist ||= wishlists.first
    default_wishlist ||= wishlists.create(name: Spree.t(:default_wishlist_name), is_default: true)
    default_wishlist.update_attribute(:is_default, true) unless default_wishlist.is_default?
    default_wishlist
  end
end

app/models/spree/variant_decorator.rb
Spree::Variant.class_eval do
  has_many :wished_products, dependent: :destroy
end

app/models/spree/wished_product.rb
class Spree::WishedProduct < ActiveRecord::Base
  if Gem.loaded_specs['spree_core'].version >= Gem::Version.create('3.3.0')
      belongs_to :variant, optional: true
      belongs_to :wishlist, optional: true
    else
      belongs_to :variant
      belongs_to :wishlist
  end

  def total
    quantity * variant.price
  end

  def display_total
    Spree::Money.new(total)
  end

end

app/models/spree/wishlist.rb
class Spree::Wishlist < ActiveRecord::Base
  belongs_to :user, class_name: Spree.user_class.to_s
  has_many :wished_products, dependent: :destroy
  before_create :set_access_hash

  validates :name, presence: true

  def include?(variant_id)
    wished_products.map(&:variant_id).include? variant_id.to_i
  end

  def to_param
    access_hash
  end

  def self.get_by_param(param)
    Spree::Wishlist.find_by_access_hash(param)
  end

  def can_be_read_by?(user)
    !self.is_private? || user == self.user
  end

  def is_default=(value)
    self[:is_default] = value
    return unless is_default?
    Spree::Wishlist.where(is_default: true, user_id: user_id).where.not(id: id).update_all(is_default: false)
  end

  def is_public?
    !self.is_private?
  end

  private

  def set_access_hash
    random_string = SecureRandom.hex(16)
    self.access_hash = Digest::SHA1.hexdigest("--#{user_id}--#{random_string}--#{Time.now}--")
  end
end

app/controllers/spree/wished_products_controller.rb
class Spree::WishedProductsController < Spree::StoreController
  respond_to :html

  def create
    @wished_product = Spree::WishedProduct.new(wished_product_attributes)
    @wishlist = spree_current_user.wishlist

    if @wishlist.include? params[:wished_product][:variant_id]
      @wished_product = @wishlist.wished_products.detect { |wp| wp.variant_id == params[:wished_product][:variant_id].to_i }
    else
      @wished_product.wishlist = spree_current_user.wishlist
      @wished_product.save
    end

    respond_with(@wished_product) do |format|
      format.html { redirect_to wishlist_url(@wishlist) }
    end
  end

  def update
    @wished_product = Spree::WishedProduct.find(params[:id])
    @wished_product.update_attributes(wished_product_attributes)

    respond_with(@wished_product) do |format|
      format.html { redirect_to wishlist_url(@wished_product.wishlist) }
    end
  end

  def destroy
    @wished_product = Spree::WishedProduct.find(params[:id])
    @wished_product.destroy

    respond_with(@wished_product) do |format|
      format.html { redirect_to wishlist_url(@wished_product.wishlist) }
    end
  end

  private

  def wished_product_attributes
    params.require(:wished_product).permit(:variant_id, :wishlist_id, :remark, :quantity)
  end
end

app/controllers/spree/wishlists_controller.rb
class Spree::WishlistsController < Spree::StoreController
  helper 'spree/products'

  before_action :find_wishlist, only: [:destroy, :show, :update, :edit]

  respond_to :html
  respond_to :js, only: :update

  def new
    @wishlist = Spree::Wishlist.new
    respond_with(@wishlist)
  end

  def index
    @wishlists = spree_current_user.wishlists
    respond_with(@wishlist)
  end

  def edit
    respond_with(@wishlist)
  end

  def update
    @wishlist.update_attributes wishlist_attributes
    respond_with(@wishlist)
  end

  def show
    respond_with(@wishlist)
  end

  def default
    @wishlist = spree_current_user.wishlist
    respond_with(@wishlist) do |format|
      format.html { render :show }
    end
  end

  def create
    @wishlist = Spree::Wishlist.new wishlist_attributes
    @wishlist.user = spree_current_user
    @wishlist.save
    respond_with(@wishlist)
  end

  def destroy
    @wishlist.destroy
    respond_with(@wishlist) do |format|
      format.html { redirect_to account_path }
    end
  end

  private

  def wishlist_attributes
    params.require(:wishlist).permit(:name, :is_default, :is_private)
  end

  # Isolate this method so it can be overwritten
  def find_wishlist
    @wishlist = Spree::Wishlist.find_by_access_hash!(params[:id])
  end
end

app/views/spree/products/_wishlist_form.html.erb
<% if spree_current_user %>
  <div id="wishlist-form">
    <%= form_for Spree::WishedProduct.new do |f| %>
      <%= f.hidden_field :variant_id, value: @product.master.id %>
      <%= f.hidden_field :quantity %>
      <button type="submit" class="btn btn-info">
        <%= Spree.t(:add_to_wishlist) %>
      </button>
    <% end %>
  </div>
<% end %>

app/views/spree/users/_wishlists.html.erb
<h3><%= Spree.t(:my_wishlists) %></h3>
<ul>
<% @user.wishlists.each do |wl| %>
  <% if !wl.is_private? || @user == spree_current_user %>
  <li><%= link_to wl.name, wl %></li>
  <% end -%>
<% end -%>
</ul>

app/views/spree/wishlists/_accessibility.html.erb
<%= form_for @wishlist, html: { class: 'ajax_form', id: 'change_wishlist_accessibility' } do |f| %>
  <%= f.radio_button :is_private, true %>&nbsp;<%= Spree.t(:private) %>
  <%= f.radio_button :is_private, false %>&nbsp;<%= Spree.t(:public) %>
<% end -%>

app/views/spree/wishlists/_mail_to_friend.text.erb
<%= mail.recipient_name %>,

<%= Spree.t(:take_a_look_at_my_wishlist) %>

  * <%= wishlist.name %>

<% unless mail.message.blank? -%>
<%= mail.message %>
<% end -%>

<%= mail.sender_name %>

<%= Spree.t(:click_link_to_view_wishlist, name: wishlist.name) %>
<%= wishlist_url(wishlist) %>

app/views/spree/wishlists/edit.html.erb
<h1 class="row"><%= Spree.t(:editing_wishlist) %></h1>
<%= form_for @wishlist do |f| %>
  <p><%= f.label :name, Spree.t(:name) %>:&nbsp;<%= f.text_field :name %></p>
  <p><%= f.check_box :is_private %>&nbsp;<%= f.label :is_private, Spree.t(:is_private) %></p>
  <p><%= f.check_box :is_default %>&nbsp;<%= f.label :is_default, Spree.t(:is_default) %></p>
  <%= f.submit Spree.t(:update) %>
  <%= Spree.t(:or) %>
  <%= link_to Spree.t(:delete_wishlist), @wishlist, method: :delete, data: { confirm: Spree.t(:are_you_sure_wishlist) }, class: 'button' %>
<% end -%>

app/views/spree/wishlists/index.html.erb
<h1 class="row"><%= Spree.t(:wishlists) %></h1>
<%= content_tag :ul do %>
  <% @wishlists.each do |wishlist| %>
    <%= content_tag :li do %>
      <%= link_to(wishlist.name, wishlist) %> - <%= wishlist.is_private ? Spree.t(:private) : Spree.t(:public) %>
    <% end %>
  <% end %>
<% end %>

app/views/spree/wishlists/new.html.erb
<h1><%= Spree.t(:creating_wishlist) %></h1>
<%= form_for @wishlist do |f| %>
  <p><%= f.label :name, Spree.t(:name) %>:&nbsp;<%= f.text_field :name %></p>
  <p><%= f.check_box :is_private %>&nbsp;<%= f.label :is_private, Spree.t(:is_private) %></p>
  <%= f.submit Spree.t(:create) %>
<% end -%>

app/views/spree/wishlists/show.html.erb
<div id="wishlist_header">
  <h1><%= @wishlist.name %></h1>
  <% if @wishlist.user == spree_current_user %>
    <div id="manage_wishlist_links">
      <%= link_to Spree.t(:edit_wishlist), edit_wishlist_path(@wishlist), class: 'button' %>
    </div>
    <div><%= render partial: 'accessibility' %></div>
  <% end -%>
</div>
<table id="wishlist" class="table table-bordered table-hover">
  <thead>
    <tr>
      <% if @wishlist.user == spree_current_user %>
        <th><%= Spree.t(:wishlist_actions) %></th>
      <% end -%>
      <th><%= Spree.t(:item_view) %></th>
      <th><%= Spree.t(:item_description) %></th>
      <th><%= Spree.t(:availability) %></th>
      <th><%= Spree.t(:date_added) %></th>
      <th><%= Spree.t(:price) %></th>
      <th><%= Spree.t(:quantity) %></th>
      <th><%= Spree.t(:total) %></th>
    </tr>
  </thead>
  <tbody id="line_items">
  <% if @wishlist.wished_products.size > 0 %>
    <% @wishlist.wished_products.each do |wish|
        variant = wish.variant
        product = variant.product %>
    <tr class="<%= cycle('', 'alt') %>">
    <% if @wishlist.user == spree_current_user %>
      <td>
        <p><%= link_to Spree.t(:remove_from_wishlist), wish, method: :delete, class: 'btn btn-danger' %></p>
        <%= form_for :order, url: populate_orders_url do |f| %>
          <%= hidden_field_tag 'variant_id', variant.id, size: 3 %>
          <%= Spree.t(:quantity) %>
          <%= number_field_tag 'quantity', wish.quantity, size: 3 %>
          <%= link_to Spree.t(:add_to_cart), '#', onclick: '$(this).parent().submit(); return false;', class: 'btn btn-success' %>
        <% end %>
        <% if spree_current_user.wishlists.count > 1 %>
          <%= Spree.t(:move_to_another_wishlist) %>:
          <%= form_for wish do |f| %>
            <%= f.select :wishlist_id, spree_current_user.wishlists.map{|wl| [wl.name, wl.id]} %>
            <%= f.submit Spree.t(:move), class: 'btn btn-default' %>
          <% end %>
        <% end %>
        <br />
      </td>
    <% end -%>
      <td>
        <% if variant.images.length == 0 %>
          <%= small_image(variant.product) %>
        <% else %>
          <%= image_tag variant.images.first.attachment.url(:small) %>
        <% end %>
      </td>
      <td>
        <h4><%= link_to product.name, product %></h4>
        <p><%= variant_options variant %></p>
        <%= truncate(strip_tags(product.description), length: 100, omission: '...') %>
      </td>
      <td>
        <%= variant.can_supply? ? Spree.t(:in_stock) : Spree.t(:out_of_stock) %>
      </td>
      <td>
        <%= wish.created_at.strftime '%m/%d/%Y' %>
      </td>
      <td>
        <%= display_price(variant) %>
      </td>
      <td>
        <%= form_for wish do |f| %>
          <%= f.number_field :quantity %>
          <%= f.submit Spree.t('actions.save'), class: 'btn btn-info '  %>
        <% end %>
      </td>
      <td>
        <%= wish.display_total %>
      </td>
    </tr>
    <% end -%>
  <% else -%>
    <tr>
      <td colspan="6"><%= Spree.t(:your_wishlist_is_empty) %></td>
    </tr>
  <% end -%>
  </tbody>
</table>
<div class="footer_links" data-hook="wishlist_footer_links">
<% if @wishlist.user == spree_current_user %>
  <%= link_to Spree.t(:create_new_wishlist), new_wishlist_path, class: 'btn btn-default' %>
<% end -%>
<%= link_to Spree.t(:continue_shopping), products_path, class: 'btn btn-default' %>
<% if respond_to?(:email_to_friend_url) %>
  <%= link_to Spree.t('email_to_friend.send_to_friend'), email_to_friend_url('wishlist', @wishlist), class: 'btn btn-default' %>
<% end %>
</div>